@isTest 
 private class AssignContactAccountOwnerWithNewCaseTest { 
    // @isTest static void noAccountNoContact() { 
    //     Case aCase = new Case();
    //     aCase.Name = 'Test Case';
    //     insert aCase;


    // }

    // @isTest static void noAccountWithContact() { 
    //     //test code goes here
    //     //remember to change class name
    // }     
    
    // @isTest static void withAccountWithContact() { 
    //     //test code goes here
    //     //remember to change class name
    // }

    // @isTest static void noAccountOrContact() { 
    //     //test code goes here
    //     //remember to change class name
    // }
}